
name: Deploy the ALDashboard to PyPI and the Dev server

on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    name: Deploy to the Development server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: SuffolkLITLab/ALActions/da_package@main
      with:
        SERVER_URL: ${{ vars.DEV_SERVER_URL }}
        DOCASSEMBLE_DEVELOPER_API_KEY: ${{ secrets.DOCASSEMBLE_DEV_SERVER_API_KEY }}
        GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}
        GITHUB_BRANCH: main
